/* Generated by bin2c, do not edit manually */
#ifndef __b9s_h_included
#define __b9s_h_included

/* Contents of file boot9strap */
//extern const long int boot9strap_size;
extern unsigned char boot9strap[30976];

#endif    /* __b9s_h_included */
